nodeLinker: node-modules

# We use Corepack instead of the local Yarn build
# See https://yarnpkg.com/configuration/yarnrc#yarnPath
# yarnPath: .yarn/releases/yarn-4.9.2.cjs

# Fixing tiptap issue
# See:
# - https://github.com/ueberdosis/tiptap/issues/3746
# - https://github.com/ueberdosis/tiptap/issues/4100
packageExtensions:
  "@tiptap/starter-kit@*":
    peerDependencies:
      "@tiptap/pm": "*"
      "@tiptap/core": "*"
