// Note: these types should be generated by the backend

export interface TestItem {
  id: string;
  title: string;
  description: string | null;
}

export interface CreateTestItem {
  title: string;
  description: string | null;
}

export interface UpdateTestItem {
  title?: string;
  description?: string | null;
}
