name: Build frontend container image

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "confiture-web-app/**"

jobs:
  build_frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log into registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: "ghcr.io/disic/confiture/web-app"
          tags: |
            type=schedule
            # type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            # add sha
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: Dockerfile.app
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            "VITE_SENTRY_DSN=${{ secrets.VITE_SENTRY_DSN }}"
            "VITE_SENTRY_ENVIRONMENT=${{ secrets.VITE_SENTRY_ENVIRONMENT }}"
            "SENTRY_ORG=${{ secrets.SENTRY_ORG }}"
            "SENTRY_PROJECT=${{ secrets.SENTRY_PROJECT }}"
            "SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}"
            "VITE_SENTRY_RELEASE=${{ github.sha }}}}"
